# SPDX-FileCopyrightText: 2025 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "HaRP"
SPDX-PackageSupplier = "Nextcloud <info@nextcloud.com>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/HaRP"

[[annotations]]
path = [".github/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  "exapps_dev/frp_0.61.1_linux_amd64.tar.gz",
  "exapps_dev/frp_0.61.1_linux_arm64.tar.gz"
]
precedence = "closest"
SPDX-FileCopyrightText = "Fatedier <fatedier@gmail.com>"
SPDX-License-Identifier = "Apache-2.0"
comment = "Files originally taken from https://github.com/fatedier/frp"

[[annotations]]
path = ["assets/cloudflare-tunnel-1.png", "assets/cloudflare-tunnel-2.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 @edorain"
SPDX-License-Identifier = "AGPL-3.0-or-later"
